---
title: "Max_entropy"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(janitor)
library(raster)
library(sf)
library(tmap)
library(tmaptools)
library(gstat)

```

```{r}
bands <- stack(here("UVVR_brt", "UVVR_Landsat_Bands.tif"))
evi <- raster(here("UVVR_brt", "UVVR_Landsat_EVI.tif"))
index <- stack(here("UVVR_brt", "UVVR_Landsat_Index.tif"))
uvvr <- raster(here("UVVR_brt", "UVVR_Landsat_UVVR.tif"))
```

# `stack` function once you separate all 7 bands from all 4 rasters. 
```{r}
bands
evi
index
uvvr
```


# Plot Rasters
 
```{r}
plot(bands)
plot(evi)
plot(index)
plot(uvvr)
```
# Check the GRS

```{r}
bands@crs
uvvr@crs
```

```{r}
wgs84 <- "+proj=longlat +datum=WGS84 +ellps=WGS84 +no_defs"
```


### UVVR 2017
```{r}
summary(uvvr, maxsamp = ncell(uvvr))
```

```{r}
uvvr_points <- rasterToPoints(uvvr, spatial = TRUE)
```

```{r}
uvvr_df <- data.frame(uvvr_points) %>% 
  clean_names()
rm(uvvr_points)



ggplot()+
  geom_raster(data = uvvr_df, aes(x = x,
                                  y = y,
                                  fill = uvvr_landsat_uvvr)) 
  coord_equal()
```











